package demo.mavenagile.slimbatch.sillybatch.domain;

import java.sql.Timestamp;

import demo.mavenagile.slimbatch.dataaccess.DataAccessUtility;

/**
 * <pre>
 * ***
 * *************************************************************************
 * *** This file was generated by DDBTools
 * *** Copyright &copy; 2003, 2009 Kano Consulting Inc.,
 * *** 
 * *** File          : demo.sample.batch.dataaccess.auto.SillyDO.java
 * *** Creation date : Tue May 23 22:14:33 EDT 2017
 * *** Version       : $Id$
 * *** 
 * *************************************************************************
 * ***
 * </pre>
 */
/**
 * <p>
 * This class represents a row of the table "Silly"
 * <ul>
 * <li><b>Table name</b> : Silly
 * <li><b>Schema</b> : null
 * <li><b>Database Catalog</b> : test
 * </ul>
 * </p>
 * <table border=0>
 * <tr>
 * <td><b>Column</b></td>
 * <td><b>Type</b></td>
 * <td><b>Size</b></td>
 * <td><b>IsNullable</b></td>
 * <td><b>DefaultValue</b></td>
 * </tr>
 * <tr>
 * <td><b>ID</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>false</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>Num</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>Square</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>Cube</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>Quartic</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>Quintic</b></td>
 * <td>INT</td>
 * <td>10</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <td><b>Flag</b></td>
 * <td>vchar</td>
 * <td>2</td>
 * <td>true</td>
 * <td>null</td>
 * </tr>
 * <tr>
 * <td><b>LastUpdate</b></td>
 * <td>TIMESTAMP</td>
 * <td>19</td>
 * <td>false</td>
 * <td>CURRENT_TIMESTAMP</td>
 * </tr>
 * </table>
 */

public class SillyDO
{
	/**
	 * RCS String
	 */
	public final static String rcs_SillyDO_java = "$Id$";

	/**
	 * Class member names
	 */
	public static final String FILD_NAME_LASTUPDATE = "LastUpdate";
	public static final String FILD_NAME_FLAG = "Flag";
	public static final String FILD_NAME_QUINTIC = "Quintic";
	public static final String FILD_NAME_QUARTIC = "Quartic";
	public static final String FILD_NAME_CUBE = "CCube";
	public static final String FILD_NAME_SQUARE = "Square";
	public static final String FILD_NAME_Num = "Num";
	public static final String FILD_NAME_ID = "ID";

	/**
	 * Class members
	 */
	protected Timestamp oLastUpdate;
	protected String oFlag;
	protected long oQuintic;
	protected long oQuartic;
	protected long oCube;
	protected long oSquare;
	protected int oNum;
	protected int oID;

	/**
	 * SillyDO Default Constructor
	 */
	public SillyDO()
	{
	}

	/**
	 * SillyDO Constructor
	 * 
	 * @param int
	 *            varID
	 */
	public SillyDO(int varID)
	{
		oID = varID;
	}

	/**
	 * SillyDO Constructor
	 * 
	 * @param varID
	 * @param varNum
	 * @param varSquare
	 * @param varCube
	 * @param varQuartic
	 * @param varQuintic
	 * @param varFlag
	 * @param varLastUpdate
	 */
	public SillyDO(int varID, int varNum, long varSquare, long varCube, long varQuartic, long varQuintic, String varFlag, Timestamp varLastUpdate)
	{
		oID = varID;
		oNum = varNum;
		oSquare = varSquare;
		oCube = varCube;
		oQuartic = varQuartic;
		oQuintic = varQuintic;
		oFlag = varFlag;
		oLastUpdate = varLastUpdate;
	}

	/**
	 * Returns ID
	 * 
	 * @return int
	 */
	public int getID()
	{
		return (oID);
	}

	/**
	 * Sets ID
	 * 
	 * @param int
	 *            varID
	 */
	public void setID(int varID)
	{
		oID = varID;
	}

	/**
	 * Returns Num
	 * 
	 * @return int
	 */
	public int getNum()
	{
		return (oNum);
	}

	/**
	 * Sets Num
	 * 
	 * @param int
	 *            varNum
	 */
	public void setNum(int varNum)
	{
		oNum = varNum;
	}

	/**
	 * Returns Square
	 * 
	 * @return int
	 */
	public long getSquare()
	{
		return (oSquare);
	}

	/**
	 * Sets Square
	 * 
	 * @param int
	 *            varSquare
	 */
	public void setSquare(long varSquare)
	{
		oSquare = varSquare;
	}

	/**
	 * Returns Cube
	 * 
	 * @return int
	 */
	public long getCube()
	{
		return (oCube);
	}

	/**
	 * Sets Cube
	 * 
	 * @param int
	 *            varCube
	 */
	public void setCube(long varCube)
	{
		oCube = varCube;
	}

	/**
	 * Returns Quartic
	 * 
	 * @return int
	 */
	public long getQuartic()
	{
		return (oQuartic);
	}

	/**
	 * Sets Quartic
	 * 
	 * @param int
	 *            varQuartic
	 */
	public void setQuartic(long varQuartic)
	{
		oQuartic = varQuartic;
	}

	/**
	 * Returns Quintic
	 * 
	 * @return int
	 */
	public long getQuintic()
	{
		return (oQuintic);
	}

	/**
	 * Sets Quintic
	 * 
	 * @param int
	 *            varQuintic
	 */
	public void setQuintic(long varQuintic)
	{
		oQuintic = varQuintic;
	}

	public String getFlag()
	{
		return oFlag;
	}

	public void setFlag(String varFlag)
	{
		oFlag = varFlag;
	}

	/**
	 * Returns LastUpdate
	 * 
	 * @return Timestamp
	 */
	public Timestamp getLastUpdate()
	{
		return (oLastUpdate);
	}

	/**
	 * Sets LastUpdate
	 * 
	 * @param Timestamp
	 *            varLastUpdate
	 */
	public void setLastUpdate(Timestamp varLastUpdate)
	{
		oLastUpdate = varLastUpdate;
	}

	/**
	 * Returns a string representation of this object
	 * 
	 * @return String
	 */
	public String toStringRows()
	{
		StringBuffer aBuffer = new StringBuffer(294);

		aBuffer.append("\n	").append(SillyDO.FILD_NAME_ID).append("	: ").append(oID);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_Num).append("	: ").append(oNum);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_SQUARE).append("	: ").append(oSquare);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_CUBE).append("	: ").append(oCube);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_QUARTIC).append("	: ").append(oQuartic);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_QUINTIC).append("	: ").append(oQuintic);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_FLAG).append("	: ").append(oFlag);
		aBuffer.append("\n	").append(SillyDO.FILD_NAME_LASTUPDATE).append("	: ").append(oLastUpdate);

		return (aBuffer.toString());
	}

	public String toString()
	{
		return (toStringCols());
	}

	/**
	 * Returns a string representation of this object in column format
	 * 
	 * @return String
	 */
	public String toStringCols()
	{
		StringBuffer aBuffer = new StringBuffer(294);

		aBuffer.append("	").append(oID);
		aBuffer.append("	").append(oNum);
		aBuffer.append("	").append(oSquare);
		aBuffer.append("	").append(oCube);
		aBuffer.append("	").append(oQuartic);
		aBuffer.append("	").append(oQuintic);
		aBuffer.append("	").append(oFlag);
		aBuffer.append("	").append(oLastUpdate);

		return (aBuffer.toString());
	}

	/**
	 * Returns an XML representation of this object
	 * 
	 * @return String
	 */
	public String toXML()
	{
		return (toXML(null, 0));
	}

	/**
	 * Returns an XML representation of this object
	 * 
	 * @return String
	 */
	public String toXML(String varTagName)
	{
		return (toXML(varTagName, 0));
	}

	/**
	 * Returns an XML representation of this object
	 * 
	 * @return String
	 */
	public String toXML(int varIndent)
	{
		return (toXML(null, varIndent));
	}

	/**
	 * Returns an XML representation of this object
	 * 
	 * @return String
	 */
	public String toXML(String varTagName, int varIndent)
	{
		StringBuffer aBuffer = new StringBuffer(294);

		int subIndent = varIndent + 1;

		if (varTagName == null)
			aBuffer.append(DataAccessUtility.getBeginTag("Silly", varIndent));
		else
			aBuffer.append(DataAccessUtility.getBeginTag(varTagName, varIndent));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_ID, oID, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_Num, oNum, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_SQUARE, oSquare, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_CUBE, oCube, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_QUARTIC, oQuartic, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_QUINTIC, oQuintic, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_FLAG, oFlag, subIndent, false));
		aBuffer.append(DataAccessUtility.getTag(SillyDO.FILD_NAME_LASTUPDATE, oLastUpdate, subIndent, false));
		if (varTagName == null)
			aBuffer.append(DataAccessUtility.getEndTag("Silly", varIndent));
		else
			aBuffer.append(DataAccessUtility.getEndTag(varTagName, varIndent));

		return (aBuffer.toString());
	}
}
